name: Build PK3
description: Builds the PK3
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: montudor/action-zip@v1
    with:
      args: zip -r "uas-alcohol-${{ env.SUFFIX }}.pk3" . -i shaders/* zscript/* GLDEFS LANGUAGE.* LICENSE MAPINFO README.md ZSCRIPT.*
